version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing Docker...
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sudo sh get-docker.sh
      - sudo usermod -aG docker $USER

  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t helloworldapp ./src
      - docker tag helloworldapp:latest $ECR_URI:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_URI:latest

artifacts:
  files: '**/*'
